codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "95...100"

status:
  project:
    default:
      target: auto
      if_no_uploads: error
    
  patch:
    default:
      target: auto
              
  changes:
    default:
      branches: null

  ignore:
    - "docs/*"
    - "tests/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
