language: python
python: 2.7

env:
  global:
    - BITCOIN_HOST=localhost
    - BITCOIN_RPCUSER=electron
    - BITCOIN_RPCPASSWORD=neutrino

install: pip install --process-dependency-links -e .[test]

before_install:
  - pip install codecov
  - sudo apt-add-repository -y ppa:bitcoin/bitcoin
  - sudo apt-get -q update
  - sudo apt-get install -y bitcoind
  - bitcoind -daemon -regtest -rpcuser=electron -rpcpassword=neutrino -txindex=1

script: py.test -v --cov

after_success: codecov
