version: '2'

services:
  spool:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      BITCOIN_HOST: bitcoin
      BITCOIN_RPCUSER: merlin
      BITCOIN_RPCPASSWORD: secret
    command: py.test --verbose
  spool-py2:
    build:
      context: .
      dockerfile: Dockerfile-py2
    volumes:
      - .:/usr/src/app
    environment:
      BITCOIN_HOST: bitcoin
      BITCOIN_RPCUSER: merlin
      BITCOIN_RPCPASSWORD: secret
    command: py.test --verbose
  bitcoin:
    image: ascribe/bitcoin
    volumes:
      -  ./bitcoin_regtest.conf:/root/.bitcoin/bitcoin.conf
    ports:
      - '18332'
      - '18333'
    command: bitcoind -regtest -printtoconsole
  bdocs:
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/docs
    command: make html
  vdocs:
    image: nginx
    ports:
      - '40084:80'
    volumes:
      - ./docs/build/html:/usr/share/nginx/html
